dist: xenial

language: node_js

cache: yarn

node_js:
    - "lts/dubnium"

install:
    - yarn

jobs:
  include:
    - stage: "Tests"
      script: yarn test:ci
      script: yarn coverage:ci
      script: yarn lint
