dist: xenial
language: node_js
cache: yarn
node_js:
- lts/dubnium
install:
- yarn
jobs:
  include:
  - stage: Tests
    script: yarn test:ci
  - script: yarn coverage:ci

deploy:
  provider: npm
  email: hq20
  api_key:
    secure: aCuj6pMtpNz+vwTTMkfgb2V7Vp1xFCRWkyQTMapJNHm9RyEaPUlAOKE3ifp5lVNFS1Az0xDJm3ud91iNKM7VgIIc49XFzKX5Qjp2sT+b7gJHQLwXZFWg9+/vj8KgicYj1Dj8/rDSggzTCnMX7iY1U1VJv2ngelhmv7RHg8tg7LYt56WViK9iGr82AW7fop22OqhzGuy2fvcTasNWciRzWND3QX3me82oAV1yAluHDH9Sp+2KU0CFALFG4ZEpLSeQVuFlVqI021pufc8h94Ii4vA5Fyky+nZk8V1eUeplZcOUiC3nKMGZWm3BTyv81vZYN/nGP4sJ5ExqsHZrt/IPz7FkJQGtEjGYLy+qspSsMbtJdY4CXs+4QJxU9xZmsaczYezRcNUXubBP1O5XrqDE/zWG2lpmdczrQQahklrDxSWzagh1PyNCNOtUJNla2WuJiXIfqzDt6s02RxpWoebJwLaGxhHtjJbAHrtjG012vy1F7J2NJ9qFk4OdHfJgR1mAdjXQUfdRr7V4GZx4M9ljfLgYoatIXwVUO/t6YE7NEoJ2FynCBzERInMtMluK26xZrJjZPGAIQkE0kcNWjQHTW1AgXs5NG/Ef5J+a5YO3kz4fIT0ydnYfTJ40YKeKrGsW5euIbAf1X1AmB0s7LOK3RWepKj+sDWn1xvi5MA82tMc=
  on:
    tags: true
    repo: HQ20/contracts
